variables:
  GIT_DEPTH: 0
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_RUNNER_SHORT_TOKEN/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME/$CI_JOB_NAME/$CI_CONCURRENT_ID

stages:
  - info
  - test

#############
### INFOS ###
#############

show-env-vars:
  stage: info
  variables:
    SEP: "##################################################################"
    S00: "commit date - "
    S01: "project: ${CI_PROJECT_PATH}"
    S02: "branch: ${CI_COMMIT_REF_NAME}"
    S03: "commit: ${CI_COMMIT_SHA}"
    S04: "commit msg: ${CI_COMMIT_MESSAGE}"
    S05: "clone base path: "
    S06: "runner token: ${CI_RUNNER_SHORT_TOKEN}"
  script: echo -e "${SEP}\n${S00}$(date)\n${SEP}\n${S01}\n${S02}\n${S03}\n${S04}\n${SEP}\n${S05}${GIT_CLONE_PATH}\n${S06}\n${SEP}"

#################
### TEST JOBS ###
#################

.common-test-job:
  stage: test
  script:
    - source $CI_JOB_NAME
    - echo FC  = $FC
    - echo F77 = $F77
    - echo CC  = $CC
    - echo CXX = $CXX
    - echo "NetCDF-C:" $(nc-config --version)
    - echo "NetCDF-F:" $(nf-config --version)
    - make --version
    - cmake --version
    - python --version
    - pip list

eve.chs-conda01:
  extends: .common-test-job

eve.chs-conda02:
  extends: .common-test-job

eve.chs-conda03:
  extends: .common-test-job

eve.chs-conda04:
  extends: .common-test-job

eve.gfortran102:
  extends: .common-test-job

eve.gfortran102MPI:
  extends: .common-test-job

eve.gfortran122:
  extends: .common-test-job

eve.gfortran122MPI:
  extends: .common-test-job

eve.intel2020b:
  extends: .common-test-job

eve.intel2020bMPI:
  extends: .common-test-job

eve.intel2023b-classic:
  extends: .common-test-job

eve.intel2023bMPI-classic:
  extends: .common-test-job

eve.intel2023b-llvm:
  extends: .common-test-job

eve.intel2023bMPI-llvm:
  extends: .common-test-job
